In [2]:
import pandas as pd 
import numpy as np

In [19]:
people_control = 500
people_treatment = 500

conversions_control = [1 if np.random.random() < 0.15 else 0 for _ in range(people_control)]
conversions_treatment = [1 if np.random.random() < 0.09 else 0 for _ in range(people_treatment)]

rate_control = len(conversions_control) / people_control
rate_treatment = len(conversions_treatment) / people_treatment

ltv_control = np.random.normal(100, 10, people_control)
ltv_treatment = np.random.normal(130, 10, people_treatment)

cost_of_acquisition = np.random.normal(50, 3, people_control)
cost_of_acquisition_treatment = np.random.normal(50, 3, people_treatment)

df_control = pd.DataFrame({
    "conversion": conversions_control,
    "ltv": ltv_control,
    "cost_of_acquisition": cost_of_acquisition
})

df_treatment = pd.DataFrame({
    "conversion": conversions_treatment,
    "ltv": ltv_treatment,
    "cost_of_acquisition": cost_of_acquisition_treatment
})

In [20]:
df_control.describe()

       conversion         ltv  cost_of_acquisition
count  500.000000  500.000000           500.000000
mean     0.148000   99.091066            50.156042
std      0.355456   10.658211             3.027816
min      0.000000   61.400517            40.841019
25%      0.000000   91.611858            47.938370
50%      0.000000   99.235151            50.191818
75%      0.000000  106.650620            52.273528
max      1.000000  128.545416            58.701159

In [21]:
df_treatment.describe()

       conversion         ltv  cost_of_acquisition
count  500.000000  500.000000           500.000000
mean     0.102000  130.125426            50.008019
std      0.302951   10.164893             3.158543
min      0.000000   99.688462            38.013021
25%      0.000000  123.429406            47.909581
50%      0.000000  130.356375            50.004111
75%      0.000000  136.641800            52.144851
max      1.000000  157.888907            59.597800